### PR TITLE
Ios web app

### PR DESCRIPTION
**Pull request by Shaun2D2**
ios web app capability added per #4

### CODE REVIEW

**Comment by mattstauffer** [comment]
At least a few years back, we needed multiple sizes of icons. Found a quick but old SO link about it:

http://stackoverflow.com/questions/2997437/what-size-should-apple-touch-icon-png-be-for-ipad-and-iphone-4

My guess is this given icon (and lack of icon meta tags) won't be enough for now. Holler if you need help in figuring out and generating higher res icons. :)

**Comment by Shaun2D2** [comment]
Hey @mattstauffer 

I was reviewing the docs from apple, it seemed like I just needed to place it in the root of public for it to work and name it correctly.  There are multiple sizes, I believe I scaled it corrected to @3x to cover all device sizes but this could be a bad strategy.  I was trying to match up the sizing correctly, my friend did the image and provided a number of different icons so I think I have all the different sizes but I think @3x was large enough to cover all of them.

here are the docs I used:

https://developer.apple.com/library/safari/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html#//apple_ref/doc/uid/TP40002051-CH3

I did successfully test on my iPhone 6S and it came through ok.  You can test if you have an iPhone on my staging server at burgermergency.whoisshaun.com.  Let me know what you think!

**Comment by mattstauffer** [comment]
Hey Shaun, iPad needs at least 152x152. But if you'r relying on a friend, I can just update it on my machine.

And yah, if you plan to offer a single image that works for everyone, you don't need the HTML. :+1:

**Comment by Shaun2D2** [comment]
Sweet, Thanks Matt!

**Pull request merged**
